-- Adicionar campos de características, tributação à tabela produtos
ALTER TABLE public.produtos
ADD COLUMN IF NOT EXISTS descricao_curta TEXT,
ADD COLUMN IF NOT EXISTS descricao_complementar TEXT,
ADD COLUMN IF NOT EXISTS observacoes TEXT,
ADD COLUMN IF NOT EXISTS tags TEXT[],
ADD COLUMN IF NOT EXISTS ncm TEXT,
ADD COLUMN IF NOT EXISTS cest TEXT,
ADD COLUMN IF NOT EXISTS origem TEXT,
ADD COLUMN IF NOT EXISTS cfop TEXT,
ADD COLUMN IF NOT EXISTS icms_cst TEXT,
ADD COLUMN IF NOT EXISTS icms_aliquota NUMERIC,
ADD COLUMN IF NOT EXISTS pis_cst TEXT,
ADD COLUMN IF NOT EXISTS pis_aliquota NUMERIC,
ADD COLUMN IF NOT EXISTS cofins_cst TEXT,
ADD COLUMN IF NOT EXISTS cofins_aliquota NUMERIC,
ADD COLUMN IF NOT EXISTS codigo_servico TEXT,
ADD COLUMN IF NOT EXISTS iss_aliquota NUMERIC;