// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Chave para armazenar configuração dinâmica no localStorage
const DYNAMIC_CONFIG_KEY = 'supabase_dynamic_config';

// Interface para configuração dinâmica
interface DynamicConfig {
  supabaseUrl?: string;
  supabaseAnonKey?: string;
  supabaseServiceRoleKey?: string;
  projectId?: string;
  destinationDatabaseUrl?: string;
  timestamp?: number;
}

// Função para obter configuração do localStorage
function getDynamicConfig(): DynamicConfig | null {
  if (typeof window === 'undefined') return null;
  
  try {
    const stored = localStorage.getItem(DYNAMIC_CONFIG_KEY);
    if (stored) {
      const config = JSON.parse(stored) as DynamicConfig;
      // Configuração válida por 24 horas
      if (config.timestamp && Date.now() - config.timestamp < 24 * 60 * 60 * 1000) {
        return config;
      }
    }
  } catch (e) {
    console.warn('Erro ao ler configuração dinâmica:', e);
  }
  
  return null;
}

// Função para salvar configuração dinâmica
export function setDynamicSupabaseConfig(
  url: string,
  anonKey: string,
  projectId?: string,
  serviceRoleKey?: string,
  destinationDatabaseUrl?: string
) {
  if (typeof window === 'undefined') return;
  
  const config: DynamicConfig = {
    supabaseUrl: url.trim(),
    supabaseAnonKey: anonKey.trim(),
    supabaseServiceRoleKey: serviceRoleKey?.trim() || undefined,
    projectId,
    destinationDatabaseUrl: destinationDatabaseUrl?.trim() || undefined,
    timestamp: Date.now(),
  };
  
  try {
    localStorage.setItem(DYNAMIC_CONFIG_KEY, JSON.stringify(config));
    console.log('✅ Configuração dinâmica do Supabase salva!');
    console.log('⚠️ Recarregue a página para aplicar as mudanças.');
  } catch (e) {
    console.error('Erro ao salvar configuração dinâmica:', e);
  }
}

// Função para limpar configuração dinâmica
export function clearDynamicSupabaseConfig() {
  if (typeof window === 'undefined') return;
  localStorage.removeItem(DYNAMIC_CONFIG_KEY);
  console.log('✅ Configuração dinâmica removida. Usando variáveis de ambiente.');
}

// Função para obter as variáveis de ambiente (com fallback para configuração dinâmica)
function getEnvVars() {
  // Primeiro, tentar usar configuração dinâmica do localStorage
  const dynamicConfig = getDynamicConfig();
  if (dynamicConfig?.supabaseUrl && dynamicConfig?.supabaseAnonKey) {
    console.log('📦 Usando configuração dinâmica do Supabase');
    return {
      projectId: dynamicConfig.projectId,
      supabaseUrl: dynamicConfig.supabaseUrl,
      supabaseAnonKey: dynamicConfig.supabaseAnonKey,
    };
  }
  
  // Fallback para variáveis de ambiente
  const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID as string | undefined;
  const configuredUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
  const supabaseUrl = configuredUrl?.trim() || (projectId ? `https://${projectId}.supabase.co` : undefined);
  const supabaseAnonKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;
  
  return { projectId, supabaseUrl, supabaseAnonKey };
}

// Função para criar o cliente Supabase
function createSupabaseClient(): SupabaseClient<Database> {
  const { supabaseUrl, supabaseAnonKey } = getEnvVars();

  if (!supabaseUrl) {
    throw new Error(
      'Supabase URL not configured. Set VITE_SUPABASE_URL or VITE_SUPABASE_PROJECT_ID in your environment.'
    );
  }

  if (!supabaseAnonKey) {
    throw new Error(
      'Supabase anon key not configured. Set VITE_SUPABASE_PUBLISHABLE_KEY in your environment.'
    );
  }

  return createClient<Database>(supabaseUrl, supabaseAnonKey, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  } as any);
}

// Cliente padrão (criado na inicialização)
let supabaseInstance: SupabaseClient<Database> | null = null;
let lastConfigHash: string | null = null;

// Função para gerar hash da configuração atual
function getConfigHash(): string {
  const vars = getEnvVars();
  const dynamicConfig = getDynamicConfig();
  return JSON.stringify({
    url: vars.supabaseUrl,
    key: vars.supabaseAnonKey ? '***' : null, // Não incluir a chave completa por segurança
    dynamic: !!dynamicConfig,
    dynamicUrl: dynamicConfig?.supabaseUrl,
  });
}

// Função para obter ou recriar o cliente
export function getSupabaseClient(): SupabaseClient<Database> {
  const currentConfigHash = getConfigHash();
  const currentVars = getEnvVars();
  
  // Sempre verificar se a configuração mudou
  if (!supabaseInstance || lastConfigHash !== currentConfigHash) {
    console.log('🔄 Criando/Recriando cliente Supabase...');
    console.log('📋 Configuração:', {
      url: currentVars.supabaseUrl,
      hasKey: !!currentVars.supabaseAnonKey,
      hasDynamicConfig: !!getDynamicConfig(),
    });
    
    supabaseInstance = createSupabaseClient();
    lastConfigHash = currentConfigHash;
    
    console.log('✅ Cliente Supabase criado com URL:', currentVars.supabaseUrl);
  }
  
  return supabaseInstance;
}

// Criar um Proxy para o cliente que sempre retorna a instância atualizada
const supabaseProxy = new Proxy({} as SupabaseClient<Database>, {
  get(_target, prop) {
    const client = getSupabaseClient();
    const value = (client as any)[prop];
    
    // Se for uma função, bind para o cliente atual
    if (typeof value === 'function') {
      return value.bind(client);
    }
    
    return value;
  },
  set(_target, prop, value) {
    const client = getSupabaseClient();
    (client as any)[prop] = value;
    return true;
  },
});

// Exportar o cliente via Proxy (sempre atualizado)
export const supabase = supabaseProxy as SupabaseClient<Database>;

// Função para forçar recriação do cliente (útil após mudanças no .env)
export function recreateSupabaseClient(): SupabaseClient<Database> {
  console.log('🔄 Forçando recriação do cliente Supabase...');
  supabaseInstance = null;
  lastConfigHash = null;
  return getSupabaseClient();
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
