// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID as string | undefined;
const configuredUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const supabaseUrl = configuredUrl?.trim() || (projectId ? `https://${projectId}.supabase.co` : undefined);
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;
const supabaseFunctionsUrl = projectId ? `https://${projectId}.functions.supabase.co` : undefined;

if (!supabaseUrl) {
  throw new Error(
    'Supabase URL not configured. Set VITE_SUPABASE_URL or VITE_SUPABASE_PROJECT_ID in your environment.'
  );
}

if (!supabaseAnonKey) {
  throw new Error(
    'Supabase anon key not configured. Set VITE_SUPABASE_PUBLISHABLE_KEY in your environment.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
} as any);
